# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 4b512db2636920f45a1bd4d0ba43c6fa0193ef02b9ebe02c0a562c7f1cde9551925c9baab8524187825dac5a1d9fb3c385192d175f108e54c3b05bcf61fded08

test:
  secret_key_base: 052794728f6f367f615f5727794ee13ef34e2b2f383c0fb22202325493f8f51da093ba80e57bb8688ecaea0c390e5fcca15caa15480ef2db47c76f5f32a27fbc

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
